### ISSUE TITLE
Hardcoded in english

### ISSUE THREAD

**Issue by dinism** [silecs/moodle-local-resourcenotif#10]
This text is hardcoded in english.
Can it be TRANSLATED? Thanks

![imagem](https://user-images.githubusercontent.com/14828021/111912002-9c13c680-8a5f-11eb-8150-aadc2224a20c.png)

**Comment by GuillaumeAllegre** [comment]
Hi Dinis,
This text is not hardcoded : the english version is the defaut value, but you can change it in the settings for local/resourcenotif.
(or just search "message_body" in Site administration search form)
