### ISSUE TITLE
Invalid property courseid

### ISSUE THREAD

**Issue by lAlejo** [silecs/moodle-local-resourcenotif#4]
When I try to send a notification, I get the following error:

Detectado un error de codificación, debe ser corregido por un programador: Invalid property courseid specified

Más información sobre este error

**Comment by ak4t0sh** [comment]
Issue reproduced using Moodle 3.1.

It seems that local_resourcenotif versions 3.1.0 & 3.1.1 are not really compatible with Moodle 3.0 & 3.1.
Indeed it use core\message\message::courseid [(lib_resourcenotif.php#L138)](https://github.com/silecs/moodle-local-resourcenotif/blob/faecbb78f53f1d1d0c6f7f02fa13ca2651e7cbe7/lib_resourcenotif.php#L138) property but this feature has been introduced starting Moodle 3.2.

Workaround : revert to release 2016081801 (https://moodle.org/plugins/pluginversions.php?plugin=local_resourcenotif)

**Comment by GuillaumeAllegre** [comment]
Indeed, the last version of this plugin (v.3.2.0, 2021-03-20) is compatible starting with Moodle 3.4+

**Comment by ak4t0sh** [comment]
![image](https://user-images.githubusercontent.com/2222386/111977231-ca96ad80-8b02-11eb-9b23-1de5df91fb11.png)
if 3.1.1 release is not compatible with Moodle 3.1 you should remove it as supported version :)

**Comment by GuillaumeAllegre** [comment]
indeed
