### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by lAlejo** [silecs/moodle-local-resourcenotif#5]
**I don't know what's wrong. I installed the plugin and get this error.** 

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, webmaster@calasanzvirtual.com and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by GuillaumeAllegre** [comment]
normally fixed since 2020 at least
