### ISSUE TITLE
I don't have the notification option in every resource

### ISSUE THREAD

**Issue by saritamg** [silecs/moodle-local-resourcenotif#9]
I've just installed the plugin and I can't see the notification option in the menu, why is that?

**Comment by GuillaumeAllegre** [comment]
Adding the notification icon is dependent upon the theme.
The plugin has been tested with the theme Boost. Normally, all the children themes are OK, but some other themes are not compatible.

Can you tell which theme you are using?

**Comment by saritamg** [comment]
The problem was mine, if I change the position of the object on the section, it doesn't show the notification button, nevertheless when I reload the page it appears again

**Comment by GuillaumeAllegre** [comment]
OK, good.
